/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Solicaitacao;

import conexão.DAOconf;
import controle.ProdutoDAO;
import controle.SolicitacaoDAO;
import entidades.Produto;
import entidades.Solicitacao;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Suelin
 */
public class Cadastrar_Solicitacao extends javax.swing.JFrame {

    /**
     * Creates new form Cadastrar_Solicitacao
     */
        long cod_fornecedor;
        float valor_t;
        SolicitacaoDAO solicitacoes;
        ProdutoDAO produtos;

        /**
         * Creates new form Cadastrar_Venda
         */
    

    public void atualizar() {
        DefaultTableModel tabela = (DefaultTableModel) tabela_solicitacao.getModel();

        int max = tabela.getRowCount();
        valor_t = 0;

        for (int i = 0; i < max; i++) {
            valor_t += (float) tabela.getValueAt(i, 2) * (int) tabela.getValueAt(i, 3);
        }
        valor_total.setText("" + valor_t);
    }

    public Cadastrar_Solicitacao(long codigo, SolicitacaoDAO solicitacoesdao, ProdutoDAO produtodao) {
        solicitacoes = solicitacoesdao;
        produtos = produtodao;
        cod_fornecedor = codigo;

        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Cadastrar Solicitação");
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);

        DefaultTableModel tabela = (DefaultTableModel) tabela_produto.getModel();
        int max = tabela.getRowCount();
        for (int i = 0; i < max; i++) {
            tabela.removeRow(0);
        }

        List<Produto> listT = produtos.listarTodos();
        for (Produto a : listT) {
            Object[] linha = {a.getId(), a.getNome(), a.getValor_compra(), a.getQuantidade()};
            tabela.addRow(linha);

        }

        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowActivated(WindowEvent e) {
                atualizar();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        data = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        multa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_produto = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela_solicitacao = new javax.swing.JTable();
        menor = new javax.swing.JToggleButton();
        maior = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        valor_total = new javax.swing.JLabel();
        cadastrar = new javax.swing.JToggleButton();
        cancelar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cadastrar Solicitação");

        jLabel2.setText("Data:");

        try {
            data.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel3.setText("Multa:");

        tabela_produto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Produto", "Valor (unid)", "Quantidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabela_produto);

        tabela_solicitacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Produto", "Valor (unid)", "Quantidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabela_solicitacao);

        menor.setText("<");
        menor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menorActionPerformed(evt);
            }
        });

        maior.setText(">");
        maior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maiorActionPerformed(evt);
            }
        });

        jLabel4.setText("Valor Total: R$");

        valor_total.setText("00,00");

        cadastrar.setText("Cadastrar");
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(multa, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cadastrar)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(menor, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                    .addComponent(maior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(cancelar)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valor_total)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(multa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(menor)
                        .addGap(18, 18, 18)
                        .addComponent(maior))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(valor_total))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastrar)
                    .addComponent(cancelar))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menorActionPerformed
        int linha = tabela_produto.getSelectedRow();
        if (linha != -1) {
            DefaultTableModel tabela1 = (DefaultTableModel) tabela_produto.getModel();
            long codigo = (long) tabela1.getValueAt(linha, 0);
            String aux = JOptionPane.showInputDialog("Digite a quantidade deste produto", "");
            if (aux.isEmpty() || aux == null) {
                JOptionPane.showMessageDialog(this.getContentPane(), "Digite uma entrada valida");
            } else {
                int quantidade = Integer.parseInt(aux);
                int quant_prod = (int) tabela1.getValueAt(linha, 3);
                if (quant_prod < quantidade) {
                    JOptionPane.showMessageDialog(this.getContentPane(), "Digite uma quantidade valida");
                } else {

                    DefaultTableModel tabela2 = (DefaultTableModel) tabela_solicitacao.getModel();
                    int max = tabela2.getRowCount();
                    int cod = -1;
                    for (int i = 0; i < max; i++) {
                        if (codigo == (long) tabela2.getValueAt(i, 0)) {
                            cod = i;
                        }
                    }
                    if (cod == -1) {
                        tabela1.setValueAt(quant_prod + quantidade, linha, 3);
                        Object[] obj = {tabela1.getValueAt(linha, 0), tabela1.getValueAt(linha, 1), tabela1.getValueAt(linha, 2), quantidade};
                        tabela2.addRow(obj);
                    } else {
                        tabela1.setValueAt(quant_prod - quantidade, linha, 3);
                        tabela2.setValueAt((int) tabela2.getValueAt(cod, 3) + quantidade, cod, 3);
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(this.getContentPane(), "Selecione um produto.");
        }
        atualizar();
    }//GEN-LAST:event_menorActionPerformed

    private void maiorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maiorActionPerformed
        int linha = tabela_solicitacao.getSelectedRow();
        if (linha != -1) {
            DefaultTableModel tabela2 = (DefaultTableModel) tabela_solicitacao.getModel();
            long codigo = (long) tabela2.getValueAt(linha, 0);
            int quant_prod = (int) tabela2.getValueAt(linha, 3);
            tabela2.removeRow(linha);

            DefaultTableModel tabela1 = (DefaultTableModel) tabela_produto.getModel();
            int max = tabela1.getRowCount();
            int aux = -1;
            for (int i = 0; i < max; i++) {
                if (codigo == (long) tabela1.getValueAt(i, 0)) {
                    aux = i;
                }
            }
            tabela1.setValueAt(((int) tabela1.getValueAt(aux, 3) - quant_prod), aux, 3);

        } else {
            JOptionPane.showMessageDialog(this.getContentPane(), "Selecione um produto.");
        }
        atualizar();
    }//GEN-LAST:event_maiorActionPerformed

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
        DefaultTableModel tabela2 = (DefaultTableModel) tabela_solicitacao.getModel();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        Date data_nascimento = null;
        try {
            data_nascimento = sdf.parse(data.getText());
        } catch (ParseException ex) {
            Logger.getLogger(Cadastrar_Solicitacao.class.getName()).log(Level.SEVERE, null, ex);
        }
        Solicitacao solicitacao = new Solicitacao(0, data_nascimento, Float.parseFloat(multa.getText())
                , Float.parseFloat(valor_total.getText()), (int) cod_fornecedor);

        String insert = "INSERT INTO solicitacao (data, multa, valor_total, fk_fornecedor)"
                + " VALUES (\'" + solicitacao.getData() + "\',\'" + solicitacao.getMulta()+ "\',"
                + solicitacao.getValor_total() + "," + solicitacao.getFk_fornecedor() + ") returning id";

        long id_solicitacao = 0;
        try {
            ResultSet insc = DAOconf.Consulta(insert);
            insc.next();
            id_solicitacao = insc.getLong("id");
        } catch (SQLException ex) {
            Logger.getLogger(Cadastrar_Solicitacao.class.getName()).log(Level.SEVERE, null, ex);
        }

        int max = tabela2.getRowCount();
        for (int i = 0; i < max; i++) {
            long cod = (long) tabela2.getValueAt(i, 0);
            insert = "insert into produto_solicitacao (id_solicitacao,id_produto,quantidade) Values "
                    + "(" + id_solicitacao + ", " + cod + ", " + tabela2.getValueAt(i, 3) + ")";
            try {
                DAOconf.execute(insert);
            } catch (SQLException ex) {
                Logger.getLogger(Cadastrar_Solicitacao.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        DefaultTableModel tabela1 = (DefaultTableModel) tabela_produto.getModel();
        max = tabela1.getRowCount();
        for (int i = 0; i < max; i++) {
            long cod = (long) tabela1.getValueAt(i, 0);
            insert = "update produto set "
                    + "quantidade=" + tabela1.getValueAt(i, 3) + " where id=" + cod;
            try {
                DAOconf.execute(insert);
            } catch (SQLException ex) {
                Logger.getLogger(Cadastrar_Solicitacao.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        dispose();
    }//GEN-LAST:event_cadastrarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton cadastrar;
    private javax.swing.JToggleButton cancelar;
    private javax.swing.JFormattedTextField data;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToggleButton maior;
    private javax.swing.JToggleButton menor;
    private javax.swing.JTextField multa;
    private javax.swing.JTable tabela_produto;
    private javax.swing.JTable tabela_solicitacao;
    private javax.swing.JLabel valor_total;
    // End of variables declaration//GEN-END:variables
}
