/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Solicaitacao;

import controle.FornecedorDAO;
import controle.ProdutoDAO;
import controle.SolicitacaoDAO;
import entidades.Fornecedor;
import entidades.Solicitacao;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Suelin
 */
public class Verificar_Sol extends javax.swing.JFrame {

    SolicitacaoDAO solicitacoes;
    ProdutoDAO produtos;
    FornecedorDAO fornecedores;
    
    public void atualizar() {
        DefaultTableModel tabela = (DefaultTableModel) tabela_solicitacao.getModel();
        int max = tabela.getRowCount();
        for (int i = 0; i < max; i++) {
            tabela.removeRow(0);
        }

        List<Solicitacao> listT = solicitacoes.listarTodos();
        for (Solicitacao a : listT) {
            Object[] linha = {a.getId(), a.getFk_fornecedor(), a.getValor_total(), a.getData()};
            tabela.addRow(linha);
        }
    }
    
    public Verificar_Sol(SolicitacaoDAO solicitacaodao, FornecedorDAO fornecedordao, ProdutoDAO produtodao) {
        solicitacoes = solicitacaodao;
        fornecedores = fornecedordao;
        produtos = produtodao;
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Solicitações");
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);

        DefaultTableModel tabela_aux = (DefaultTableModel) tabela_fornecedores.getModel();
        int max = tabela_aux.getRowCount();
        for (int i = 0; i < max; i++) {
            tabela_aux.removeRow(0);
        }

        List<Fornecedor> listTeste = fornecedores.listarTodos();
        for (Fornecedor a : listTeste) {
            Object[] linha = {a.getId(), a.getNome()};
            tabela_aux.addRow(linha);
        }

        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowActivated(WindowEvent e) {
                atualizar();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_solicitacao = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela_fornecedores = new javax.swing.JTable();
        visualizar = new javax.swing.JToggleButton();
        cadastrar = new javax.swing.JToggleButton();
        excluir = new javax.swing.JToggleButton();
        fechar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Verificar Solicitação");

        tabela_solicitacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código Solicitação", "Código Fornecedor", "Valor Total", "Data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabela_solicitacao);

        tabela_fornecedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código Fornecedor", "Nome Fornecedor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabela_fornecedores);

        visualizar.setText("Visualizar");
        visualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualizarActionPerformed(evt);
            }
        });

        cadastrar.setText("Cadastrar");
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });

        excluir.setText("Excluir");
        excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirActionPerformed(evt);
            }
        });

        fechar.setText("Fechar");
        fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(visualizar)
                        .addGap(18, 18, 18)
                        .addComponent(cadastrar)
                        .addGap(18, 18, 18)
                        .addComponent(excluir)
                        .addGap(29, 29, 29)
                        .addComponent(fechar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(visualizar)
                    .addComponent(cadastrar)
                    .addComponent(excluir)
                    .addComponent(fechar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void visualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualizarActionPerformed
        int linha = tabela_solicitacao.getSelectedRow();
        if (linha != -1) {
            DefaultTableModel tabela1 = (DefaultTableModel) tabela_solicitacao.getModel();
            Long codigo = (Long) tabela1.getValueAt(linha, 0);
            Solicitacao solicitacao = solicitacoes.buscar(codigo);
            Visualizar_Solicitacao Ver = new Visualizar_Solicitacao(solicitacao, fornecedores, solicitacoes);
            Ver.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this.getContentPane(), "Selecione uma linha.");
        }
    }//GEN-LAST:event_visualizarActionPerformed

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
        int linha = tabela_fornecedores.getSelectedRow();
        if (linha != -1) {
            DefaultTableModel tabela1 = (DefaultTableModel) tabela_fornecedores.getModel();
            long codigo = (long) tabela1.getValueAt(linha, 0);            
            Cadastrar_Solicitacao Ver = new Cadastrar_Solicitacao(codigo,solicitacoes,produtos);
            Ver.setVisible(true);            
        }else{
            JOptionPane.showMessageDialog(this.getContentPane(), "Selecione uma linha em solicitações.");
        }
    }//GEN-LAST:event_cadastrarActionPerformed

    private void excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirActionPerformed
        int linha = tabela_solicitacao.getSelectedRow();
        if (linha != -1) {
            DefaultTableModel tabela1 = (DefaultTableModel) tabela_solicitacao.getModel();
            long codigo = (long) tabela1.getValueAt(linha, 0);
            System.out.println("Excluiu id = "+codigo+" ? "+solicitacoes.remover(codigo));
            atualizar();
        }else{
            JOptionPane.showMessageDialog(this.getContentPane(),"Selecione uma linha.");
        }
    }//GEN-LAST:event_excluirActionPerformed

    private void fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecharActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_fecharActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton cadastrar;
    private javax.swing.JToggleButton excluir;
    private javax.swing.JToggleButton fechar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tabela_fornecedores;
    private javax.swing.JTable tabela_solicitacao;
    private javax.swing.JToggleButton visualizar;
    // End of variables declaration//GEN-END:variables
}
