/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Vendas;

import conexão.DAOconf;
import controle.ProdutoDAO;
import controle.VendasDAO;
import entidades.Produto;
import entidades.Vendas;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author seven
 */
public class Cadastrar_Venda extends javax.swing.JFrame {

    long cod;
    VendasDAO vendas;
    ProdutoDAO produtos;
    List<Produto> prod = new ArrayList<Produto>();

    /**
     * Creates new form Cadastrar_Venda
     */
    public void atualizar() {
        DefaultTableModel tabela = (DefaultTableModel) tabela_produto.getModel();
        int max = tabela.getRowCount();
        for (int i = 0; i < max; i++) {
            tabela.removeRow(0);
        }

        List<Produto> listT = produtos.listarTodos();
        for (Produto a : listT) {
            Object[] linha = {a.getId(), a.getNome(), a.getValor_venda(), a.getQuantidade()};
            tabela.addRow(linha);
        }
    }

    public Cadastrar_Venda(long codigo, VendasDAO vendasdao, ProdutoDAO produtodao) {
        vendas = vendasdao;
        produtos = produtodao;
        cod = codigo;
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Cadastrar Venda");
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);

        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowActivated(WindowEvent e) {
                atualizar();
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_venda = new javax.swing.JTable();
        cancelar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        cadastrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel_valor_total = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela_produto = new javax.swing.JTable();
        menor = new javax.swing.JButton();
        maior = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cadastrar Venda");

        tabela_venda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Produto", "Valor(uni)", "Quantidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabela_venda);

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        cadastrar.setText("Cadastrar");

        jLabel5.setText("Valor Total: R$");

        jLabel_valor_total.setText("00.00");

        tabela_produto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Produto", "Valor(uni)", "Quantidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabela_produto);

        menor.setText("<");
        menor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menorActionPerformed(evt);
            }
        });

        maior.setText(">");
        maior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maiorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(menor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maior, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_valor_total)
                        .addGap(32, 32, 32)
                        .addComponent(cadastrar)
                        .addGap(18, 18, 18)
                        .addComponent(cancelar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(328, 328, 328))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(menor)
                        .addGap(9, 9, 9)
                        .addComponent(maior)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel_valor_total)
                    .addComponent(cancelar)
                    .addComponent(cadastrar))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cancelarActionPerformed

    private void menorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menorActionPerformed
        int linha = tabela_produto.getSelectedRow();
        if (linha != -1) {
            DefaultTableModel tabela1 = (DefaultTableModel) tabela_produto.getModel();
            long codigo = (long) tabela1.getValueAt(linha, 0);
            String aux = JOptionPane.showInputDialog("Digite a quantidade deste produto", "");
            if (aux.isEmpty() || aux == null) {
                JOptionPane.showMessageDialog(this.getContentPane(), "Digite uma entrada valida");
            } else {
                int quantidade = Integer.parseInt(aux);
                System.out.println(quantidade);
                try {
                    ResultSet quant = DAOconf.Consulta("select * from produto where produto.id=" + aux);
                    quant.next();
                    int quant_prod = quant.getInt("quantidade");
                    if (quant_prod < quantidade) {
                        JOptionPane.showMessageDialog(this.getContentPane(), "Digite uma quantidade valida");
                    } else {
                        Produto c = new Produto(quant.getLong(1), quant.getString(2), quant.getString(3), quant_prod, quant.getFloat(5), quant.getFloat(6), quant.getInt(7));
                        prod.add(c);
                        tabela1.setValueAt(quantidade - quant_prod, linha, 3);
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Cadastrar_Venda.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this.getContentPane(), "Selecione um produto.");
        }
    }//GEN-LAST:event_menorActionPerformed

    private void maiorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maiorActionPerformed
        int linha = tabela_venda.getSelectedRow();
        if (linha != -1) {
            DefaultTableModel tabela1 = (DefaultTableModel) tabela_venda.getModel();
            long codigo = (long) tabela1.getValueAt(linha, 0);

        } else {
            JOptionPane.showMessageDialog(this.getContentPane(), "Selecione um produto.");
        }
    }//GEN-LAST:event_maiorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrar;
    private javax.swing.JButton cancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_valor_total;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton maior;
    private javax.swing.JButton menor;
    private javax.swing.JTable tabela_produto;
    private javax.swing.JTable tabela_venda;
    // End of variables declaration//GEN-END:variables
}
