/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Caixa;

import Interface.Principal;
import conexão.DAOconf;
import controle.CaixaDAO;
import controle.DespesaDAO;
import controle.VendasDAO;
import entidades.Caixa;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author seven
 */
public class Visualizar_Caixa extends javax.swing.JFrame {

    float saldo_f;
    float saldo_aplicado=0;
    float total_v;
    float total_d;
    VendasDAO vendas;
    CaixaDAO caixas;
    DespesaDAO despesas;

    public void atualizar() {
        DefaultTableModel tabela_aux = (DefaultTableModel) tabela_caixas.getModel();
        int max = tabela_aux.getRowCount();
        for (int i = 0; i < max; i++) {
            tabela_aux.removeRow(0);
        }

        List<Caixa> listTeste = caixas.listarTodos();
        for (Caixa a : listTeste) {
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            String data1, data2 = null;
            data1 = sdf.format(a.getData());
            data2 = sdf.format(a.getData_f());
            Object[] linha = {a.getId(), a.getSaldo_incial(), a.getSaldo_aplicado(), a.getSaldo_final(), a.getData(), a.getData_f()};
            tabela_aux.addRow(linha);
        }
    }

    /**
     * Creates new form Visualizar_Caixa
     */
    public Visualizar_Caixa(CaixaDAO caixadao, DespesaDAO despesadao, VendasDAO vendasdao) {
        vendas = vendasdao;
        despesas = despesadao;
        caixas = caixadao;
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Caixa");
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);

        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        Date date = new Date();
        data_caixa.setText(dateFormat.format(date));

        total_v = 0;
        total_d = 0;
        try {
            DefaultTableModel tabela_v = (DefaultTableModel) tabela_vendas.getModel();
            ResultSet rs = DAOconf.Consulta("Select * from venda where ativo = true and data=\'" + data_caixa.getText() + "\'");
            while (rs.next()) {

                Object[] linha = {rs.getLong("id"), rs.getFloat("valor_total"), rs.getDate("data")};
                tabela_v.addRow(linha);
                total_v += rs.getFloat("valor_total");
            }
            total_vendas.setText("" + total_v);
        } catch (SQLException ex) {
            Logger.getLogger(Visualizar_Caixa.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            DefaultTableModel tabela_d = (DefaultTableModel) tabela_dispesas.getModel();
            ResultSet rs = DAOconf.Consulta("Select * from despesas where ativo = true and data_pagamento=\'" + data_caixa.getText() + "\'");
            while (rs.next()) {

                Object[] linha = {rs.getLong("id"), rs.getFloat("valor_pagar"), rs.getDate("data_pagamento")};
                tabela_d.addRow(linha);
                total_d += rs.getFloat("valor_pagar");
            }
            total_dispesas.setText("" + total_d);
        } catch (SQLException ex) {
            Logger.getLogger(Visualizar_Caixa.class.getName()).log(Level.SEVERE, null, ex);
        }

//        saldo_inicial.setText(""+);
        saldo_f = Float.parseFloat(total_vendas.getText()) - Float.parseFloat(total_dispesas.getText()) + Float.parseFloat(saldo_inicial.getText());
        saldo_atual.setText("" + (Float.parseFloat(total_vendas.getText()) - Float.parseFloat(total_dispesas.getText()) + Float.parseFloat(saldo_inicial.getText())));

        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowActivated(WindowEvent e) {
                atualizar();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_vendas = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela_dispesas = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabela_caixas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        data_caixa = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        total_vendas = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        total_dispesas = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        saldo_inicial = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        saldo_atual = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton_sair = new javax.swing.JButton();
        fechar_caixa = new javax.swing.JButton();
        aplicar_saldo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabela_vendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Valor", "Data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela_vendas.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabela_vendas);

        tabela_dispesas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Valor", "Data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela_dispesas.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tabela_dispesas);

        tabela_caixas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Saldo Inicial", "Saldo Aplicado", "Saldo Final", "Abertura", "Fechamento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela_caixas.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tabela_caixas);

        jLabel1.setText("Data:");

        data_caixa.setText("--/--/----");

        jLabel3.setText("Vendas");

        jLabel4.setText("Despesas");

        jLabel5.setText("Historico de caixas");

        jLabel6.setText("Total:");

        total_vendas.setText("0");

        jLabel2.setText("Total:");

        total_dispesas.setText("0");

        jLabel7.setText("Saldo Inicial:");

        saldo_inicial.setText("0");

        jLabel9.setText("R$");

        jLabel10.setText("R$");

        jLabel11.setText("R$");

        jLabel12.setText("Saldo Atual:");

        saldo_atual.setText("0");

        jLabel13.setText("R$");

        jButton_sair.setText("Sair");
        jButton_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_sairActionPerformed(evt);
            }
        });

        fechar_caixa.setText("Fechar Caixa");
        fechar_caixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechar_caixaActionPerformed(evt);
            }
        });

        aplicar_saldo.setText("Aplicar Saldo");
        aplicar_saldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aplicar_saldoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel3)
                .addGap(228, 228, 228)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 367, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(178, 178, 178))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(data_caixa)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel12)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(saldo_atual)
                        .addGap(46, 46, 46)
                        .addComponent(aplicar_saldo)
                        .addGap(18, 18, 18)
                        .addComponent(fechar_caixa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_sair))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(saldo_inicial))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(total_vendas)
                                .addGap(206, 206, 206)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(total_dispesas)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(total_vendas)
                    .addComponent(jLabel2)
                    .addComponent(total_dispesas)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(data_caixa)
                    .addComponent(jLabel12)
                    .addComponent(saldo_atual)
                    .addComponent(jLabel13)
                    .addComponent(jButton_sair)
                    .addComponent(fechar_caixa)
                    .addComponent(aplicar_saldo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(saldo_inicial)
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_sairActionPerformed
        // TODO add your handling code here
        dispose();
    }//GEN-LAST:event_jButton_sairActionPerformed

    private void aplicar_saldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aplicar_saldoActionPerformed
        String aux = JOptionPane.showInputDialog("Digite a quantia que será aplicada.", "");
        if (aux.isEmpty() || aux == null) {
            JOptionPane.showMessageDialog(this.getContentPane(), "Digite uma entrada valida");
        } else {
            saldo_f += Float.parseFloat(aux);
            saldo_atual.setText("" + saldo_f);
            saldo_aplicado+= Float.parseFloat(aux);
        }
    }//GEN-LAST:event_aplicar_saldoActionPerformed

    private void fechar_caixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechar_caixaActionPerformed
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        Date data = null;
        
        try {
            data = sdf.parse(data_caixa.getText());
        } catch (ParseException ex) {
            Logger.getLogger(Visualizar_Caixa.class.getName()).log(Level.SEVERE, null, ex);
        }
        

        Caixa c = new Caixa(0, Float.parseFloat(saldo_atual.getText()), data, Float.parseFloat(saldo_inicial.getText()), saldo_aplicado, data);
        System.out.println("Inseriu Caixa? "+caixas.inserir(c));
        
    }//GEN-LAST:event_fechar_caixaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aplicar_saldo;
    private javax.swing.JLabel data_caixa;
    private javax.swing.JButton fechar_caixa;
    private javax.swing.JButton jButton_sair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel saldo_atual;
    private javax.swing.JLabel saldo_inicial;
    private javax.swing.JTable tabela_caixas;
    private javax.swing.JTable tabela_dispesas;
    private javax.swing.JTable tabela_vendas;
    private javax.swing.JLabel total_dispesas;
    private javax.swing.JLabel total_vendas;
    // End of variables declaration//GEN-END:variables
}
