/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interface.Estoque;

import Interface.Estoque.Cadastrar_Produto;
import java.awt.List;
import java.util.ArrayList;
import java.util.LinkedList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author seven
 */
public class Verificar_Estoque extends javax.swing.JFrame {

    /**
     * Creates new form Verificar_Estoque
     */
    public Verificar_Estoque() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Estoque");
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        //Estoque a = new Estoque();
        //List<Estoque> listEstoque = (List<Estoque>) a.Verificar_Estoque();
        //DefaultTableModel tabela = (DefaultTableModel) jTable_Lista_Produtos.getModel();
        //if(!est.isEmpty()){
//             for(Estoque p : est){
//                Object[] linha = {p.getIdEstoque(), p.getProduto(), p.getQtde(), p.getValor()};
//                tabela_estoque2.addRow(linha);
//            }
//        }
//        else
//            JOptionPane.showMessageDialog(null, "Nã existe Produtos Cadastrados", null, 0);

        
        //Teste
        ArrayList<Integer> listTeste = new ArrayList<>();
        listTeste.add(1);
        listTeste.add(3);
        listTeste.add(5);
        listTeste.add(2);
        listTeste.add(2);
        listTeste.add(2);
        listTeste.add(2);
        listTeste.add(2);
        listTeste.add(2);
        listTeste.add(2);
        listTeste.add(2);
        DefaultTableModel tabela = (DefaultTableModel) jTable_Lista_Produtos.getModel();
        if(!listTeste.isEmpty()){
            for(Integer a: listTeste){
                Object[] linha = {a,a,a,a,a};
                tabela.addRow(linha);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Lista_Produtos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton_Editar = new javax.swing.JButton();
        jButton_Cadastrar = new javax.swing.JButton();
        jButton_Fechar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable_Lista_Produtos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "Quantidade", "Valor", "Fabricante"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_Lista_Produtos);

        jLabel1.setText("Estoque");

        jButton_Editar.setText("Visualizar");
        jButton_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EditarActionPerformed(evt);
            }
        });

        jButton_Cadastrar.setText("Cadastrar");
        jButton_Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CadastrarActionPerformed(evt);
            }
        });

        jButton_Fechar.setText("Fechar");
        jButton_Fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_FecharActionPerformed(evt);
            }
        });

        jButton1.setText("Excluir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(169, 169, 169)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jButton_Editar)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_Cadastrar)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_Fechar)))
                        .addGap(0, 39, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Editar)
                    .addComponent(jButton_Cadastrar)
                    .addComponent(jButton_Fechar)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_FecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_FecharActionPerformed
        dispose();
    }//GEN-LAST:event_jButton_FecharActionPerformed

    private void jButton_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EditarActionPerformed
        // TODO add your handling code here:
        Visualizar_Produto editar = new Visualizar_Produto();
        editar.setVisible(true);
    }//GEN-LAST:event_jButton_EditarActionPerformed

    private void jButton_CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CadastrarActionPerformed
        // TODO add your handling code here:
        Cadastrar_Produto cadastrar = new Cadastrar_Produto();
        cadastrar.setVisible(true);
    }//GEN-LAST:event_jButton_CadastrarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Excluir_produto ex = new Excluir_produto();
        ex.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_Cadastrar;
    private javax.swing.JButton jButton_Editar;
    private javax.swing.JButton jButton_Fechar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Lista_Produtos;
    // End of variables declaration//GEN-END:variables
}
